apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: test-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: development
  source:
    path: k8s/charts/test-app/
    repoURL: https://github.com/bakavets/demo-temp.git
    targetRevision: {{ .Values.targetRevision }}

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
