targetRevision: main

awsRegion: eu-west-1

domain: example.com

externalDNS:
  domain: example@example.com
  txtOwnerId: Z049EXAMPLE
  serviceAccount:
    name: external-dns
    eksRoleARN: arn:aws:iam::12345678912:role/external-dns
  namespace: kube-system
