targetRevision: main

awsRegion: eu-west-1

domain: example.com

certManager_sa_eks_role_arn: arn:aws:iam::12345678901:role/cert-manager-role

externalDNS:
  domain: example@example.com
  txtOwnerId: Z049EXAMPLE
  serviceAccount:
    name: external-dns
    eksRoleARN: arn:aws:iam::12345678912:role/external-dns
  namespace: kube-system
